
TRADING_PAIRS = [
    "btcusdt", "ethusdt", "xrpusdt", "solusdt", "btcusdc", "bnbusdt", "1000pepeusdt",
    "auctionusdt", "1000xusdt", "dogeusdt", "ethusdc", "adausdt", "bnxusdt", "fartcoinusdt",
    "suiusdt", "trumpusdt", "bananausdt", "cakeusdt", "xrpusdc", "linkusdt", "vidtusdt",
    "arcusdt", "avaxusdt", "ltcusdt", "tonusdt", "enausdt", "penguusdt", "solusdc",
    "api3usdt", "aaveusdt", "redusdt", "omusdt", "wifusdt", "pnutusdt", "trxusdt",
    "eosusdt", "zrousdt", "vanausdt", "zerebrousdt", "wldusdt", "kaitousdt", "dotusdt",
    "xlmusdt", "hbarusdt", "filusdt", "1000bonkusdt", "ondousdt", "uniusdt", "bchusdt",
    "susdt", "taousdt", "alchusdt", "tiausdt", "neirousdt", "layerusdt", "nearusdt",
    "popcatusdt", "tstusdt", "bnbusdc", "ordiusdt", "notusdt", "1000shibusdt", "rareusdt",
    "ai16zusdt", "ldousdt", "crvusdt", "etcusdt", "opusdt", "aptusdt", "arkmusdt",
    "atomusdt", "melaniausdt", "raysolusdt", "jupusdt", "arbusdt", "ipusdt", "pendleusdt",
    "ethfiusdt", "moveusdt", "injusdt", "suiusdc", "1000cheemsusdt", "griffainusdt", "galausdt",
    "ethbtc", "dogeusdc", "berausdt", "mkrusdt", "fetusdt", "aixbtusdt", "1000pepeusdc",
    "virtualusdt", "swarmsusdt", "komausdt", "seiusdt", "dogsusdt", "gmtusdt", "theusdt",
    "vineusdt", "apeusdt", "eigenusdt", "algousdt", "ensusdt", "shellusdt", "sandusdt",
    "dymusdt", "beamxusdt", "kavausdt", "dfusdt", "peopleusdt", "jtousdt", "trbusdt",
    "goatusdt", "linkusdc", "1000flokiusdt", "dydxusdt", "spxusdt", "epicusdt", "kasusdt",
    "hmstrusdt", "renderusdt", "biousdt", "runeusdt", "bakeusdt", "linausdt", "zenusdt",
    "altusdt", "usualusdt", "turbousdt", "avaaiusdt", "bomeusdt", "polusdt", "fxsusdt",
    "solvusdt", "uxlinkusdt", "1000satsusdt", "gpsusdt", "idusdt", "cfxusdt", "stxusdt",
    "actusdt", "sagausdt", "cetususdt", "1000whyusdt", "thetausdt", "velodromeusdt", "vetusdt",
    "neiroethusdt", "wusdt", "1000bonkusdc", "strkusdt", "qtumusdt", "arusdt", "chillguyusdt",
    "avaxusdc", "cookieusdt", "mewusdt", "vicusdt", "1000ratsusdt", "grtusdt", "sunusdt",
    "bigtimeusdt", "memeusdt", "mantausdt", "ltcusdc", "eduusdt", "manausdt", "iousdt",
    "wifusdc", "icpusdt", "xmrusdt", "rsrusdt", "jasmyusdt", "maskusdt", "adausdc",
    "1mbabydogeusdt", "scrtusdt", "moodengusdt", "sushiusdt", "agldusdt", "spellusdt", "magicusdt",
    "ckbusdt", "wldusdc", "rdntusdt", "neousdt", "xaiusdt", "rezusdt", "cotiusdt", "enausdc",
    "zkusdt", "umausdt", "imxusdt", "flowusdt", "vvvusdt", "catiusdt", "omniusdt", "enjusdt",
    "animeusdt", "achusdt", "scrusdt", "cowusdt", "pythusdt", "nmrusdt", "heiusdt", "dexeusdt",
    "snxusdt", "driftusdt", "tnsrusdt", "c98usdt", "zilusdt", "trumpusdc", "iotausdt", "glmusdt",
    "listausdt", "acxusdt", "chzusdt", "1000catusdt", "tiausdc", "zrxusdt", "aerousdt", "lptusdt",
    "ssvusdt", "grassusdt", "blurusdt", "lqtyusdt", "luna2usdt", "alpacausdt", "pippinusdt",
    "axsusdt", "vanryusdt", "aliceusdt", "aevousdt", "yfiusdt", "chrusdt", "combousdt",
    "1000000mogusdt", "highusdt", "meusdt", "storjusdt", "btcdomusdt", "morphousdt", "sklusdt",
    "xvsusdt", "cyberusdt", "bchusdc", "hifiusdt", "compusdt", "arbusdc", "iostusdt", "usdcusdt",
    "tusdt", "1000luncusdt", "sonicusdt", "egldusdt", "b3usdt", "dusdt", "hftusdt", "aiusdt",
    "nearusdc", "zecusdt", "oneusdt", "kaitousdc", "bbusdt", "superusdt", "aergousdt", "1inchusdt",
    "pixelusdt", "brettusdt", "troyusdt", "rvnusdt", "xtzusdt", "aktusdt", "minausdt", "phausdt",
    "atausdt", "crvusdc", "gmxusdt", "ordiusdc", "roseusdt", "synusdt", "fidausdt", "yggusdt",
    "sysusdt", "qntusdt", "axlusdt", "celousdt", "1000shibusdc", "ghstusdt", "filusdc", "ethfiusdc",
    "avausdt", "aceusdt", "batusdt", "degousdt", "arkusdt", "myrousdt", "safeusdt", "xvgusdt",
    "woousdt", "portalusdt", "hookusdt", "astrusdt", "arpausdt", "zetausdt", "badgerusdt",
    "ksmusdt", "diausdt", "twtusdt", "rlcusdt", "ontusdt", "tokenusdt", "cgptusdt", "belusdt",
    "sxpusdt", "gtcusdt", "mocausdt", "nulsusdt", "banusdt", "leverusdt", "kdausdt", "rplusdt",
    "dentusdt", "hotusdt", "iotxusdt", "lrcusdt", "flmusdt", "bicousdt", "ankrusdt", "metisusdt",
    "ntrnusdt", "ipusdc", "oxtusdt", "ponkeusdt", "promusdt", "lumiusdt", "ctsiusdt", "rifusdt",
    "degenusdt", "sfpusdt", "nfpusdt", "joeusdt", "phbusdt", "kaiausdt", "hiveusdt", "celrusdt",
    "movrusdt", "polyxusdt", "stgusdt", "bswusdt", "powrusdt", "dashusdt", "gasusdt", "duskusdt",
    "bandusdt", "mavusdt", "steemusdt", "vthousdt", "bomeusdc", "swellusdt", "icxusdt", "chessusdt",
    "ognusdt", "ustcusdt", "alphausdt", "truusdt", "neousdc", "mboxusdt", "kncusdt", "ilvusdt",
    "tlmusdt", "mtlusdt", "santosusdt", "hbarusdc", "roninusdt", "1000xecusdt", "lskusdt",
    "slerfusdt", "pnutusdc", "perpusdt", "quickusdt", "waxpusdt", "ethwusdt", "kmnousdt", "orcausdt",
    "nknusdt", "cosusdt", "bntusdt", "bsvusdt", "voxelusdt", "fioustdt", "gusdt", "hippousdt",
    "ongusdt", "reiusdt", "balusdt", "defiusdt", "dodoxusdt", "lokausdt", "fluxusdt"
]